// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	schema "github.com/openboundary/openboundary/internal/schema"
	mock "github.com/stretchr/testify/mock"
)

// MockSchema is an autogenerated mock type for the Schema type
type MockSchema struct {
	mock.Mock
}

type MockSchema_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchema) EXPECT() *MockSchema_Expecter {
	return &MockSchema_Expecter{mock: &_m.Mock}
}

// Kind provides a mock function with no fields
func (_m *MockSchema) Kind() schema.Kind {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 schema.Kind
	if rf, ok := ret.Get(0).(func() schema.Kind); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(schema.Kind)
	}

	return r0
}

// MockSchema_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockSchema_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockSchema_Expecter) Kind() *MockSchema_Kind_Call {
	return &MockSchema_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockSchema_Kind_Call) Run(run func()) *MockSchema_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSchema_Kind_Call) Return(_a0 schema.Kind) *MockSchema_Kind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchema_Kind_Call) RunAndReturn(run func() schema.Kind) *MockSchema_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: spec
func (_m *MockSchema) Validate(spec map[string]interface{}) error {
	ret := _m.Called(spec)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSchema_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockSchema_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - spec map[string]interface{}
func (_e *MockSchema_Expecter) Validate(spec interface{}) *MockSchema_Validate_Call {
	return &MockSchema_Validate_Call{Call: _e.mock.On("Validate", spec)}
}

func (_c *MockSchema_Validate_Call) Run(run func(spec map[string]interface{})) *MockSchema_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *MockSchema_Validate_Call) Return(_a0 error) *MockSchema_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchema_Validate_Call) RunAndReturn(run func(map[string]interface{}) error) *MockSchema_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchema creates a new instance of MockSchema. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchema(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchema {
	mock := &MockSchema{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
