with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/openboundary/openboundary/internal/schema:
    interfaces:
      Schema:
  github.com/openboundary/openboundary/internal/parser:
    interfaces:
      Node:
