package typescript

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/stack-bound/stack-bound/internal/codegen"
	"github.com/stack-bound/stack-bound/internal/ir"
)

// SchemaGenerator copies schema files to the generated project.
type SchemaGenerator struct{}

// NewSchemaGenerator creates a new schema generator.
func NewSchemaGenerator() *SchemaGenerator {
	return &SchemaGenerator{}
}

// Name returns the generator name.
func (g *SchemaGenerator) Name() string {
	return "typescript-schemas"
}

// Generate copies schema files from the source project to the output.
// All configuration files are colocated with their components.
func (g *SchemaGenerator) Generate(i *ir.IR) (*codegen.Output, error) {
	output := codegen.NewOutput()

	// Copy Drizzle schema colocated with postgres component
	for _, comp := range i.Components {
		if comp.Kind == ir.KindPostgres && comp.Postgres != nil && comp.Postgres.Schema != "" {
			content, err := g.readSourceFile(i.BaseDir, comp.Postgres.Schema)
			if err == nil {
				filename := fmt.Sprintf("src/components/postgres/%s.schema.ts", sanitizeFilename(comp.ID))
				output.AddFile(filename, content)
			}
		}
	}

	// Copy middleware config files colocated with middleware components
	for _, comp := range i.Components {
		if comp.Kind == ir.KindMiddleware && comp.Middleware != nil {
			mwFilename := sanitizeFilename(comp.ID)
			switch comp.Middleware.Provider {
			case "better-auth":
				if comp.Middleware.Config != "" {
					content, err := g.readSourceFile(i.BaseDir, comp.Middleware.Config)
					if err == nil {
						filename := fmt.Sprintf("src/components/middlewares/%s.config.ts", mwFilename)
						output.AddFile(filename, content)
					}
				}
			case "casbin":
				if comp.Middleware.Model != "" {
					content, err := g.readSourceFile(i.BaseDir, comp.Middleware.Model)
					if err == nil {
						filename := fmt.Sprintf("src/components/middlewares/%s.model.conf", mwFilename)
						output.AddFile(filename, content)
					}
				}
				if comp.Middleware.Policy != "" {
					content, err := g.readSourceFile(i.BaseDir, comp.Middleware.Policy)
					if err == nil {
						filename := fmt.Sprintf("src/components/middlewares/%s.policy.csv", mwFilename)
						output.AddFile(filename, content)
					}
				}
			}
		}
	}

	// Generate .env.example
	output.AddFile(".env.example", []byte(g.generateEnvExample(i)))

	return output, nil
}

func (g *SchemaGenerator) readSourceFile(baseDir, relativePath string) ([]byte, error) {
	fullPath := relativePath
	if !filepath.IsAbs(relativePath) {
		fullPath = filepath.Join(baseDir, relativePath)
	}
	return os.ReadFile(fullPath)
}

func (g *SchemaGenerator) generateEnvExample(i *ir.IR) string {
	var content string
	content += "# Generated by Stack Bound\n"
	content += "# Copy this file to .env and fill in the values\n\n"

	// Add DATABASE_URL if postgres is used
	for _, comp := range i.Components {
		if comp.Kind == ir.KindPostgres {
			content += "# Database connection string\n"
			content += "DATABASE_URL=postgres://user:password@localhost:5432/dbname\n\n"
			break
		}
	}

	return content
}
