// Copyright 2026 OpenBoundary Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package typescript

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/openboundary/openboundary/internal/codegen"
	"github.com/openboundary/openboundary/internal/ir"
)

// SchemaGenerator copies schema files to the generated project.
type SchemaGenerator struct{}

// NewSchemaGenerator creates a new schema generator.
func NewSchemaGenerator() *SchemaGenerator {
	return &SchemaGenerator{}
}

// Name returns the generator name.
func (g *SchemaGenerator) Name() string {
	return "typescript-schemas"
}

// Generate copies schema files from the source project to the output.
// All configuration files are colocated with their components.
func (g *SchemaGenerator) Generate(i *ir.IR) (*codegen.Output, error) {
	output := codegen.NewOutput()

	// Copy Drizzle schema colocated with postgres component
	for _, comp := range i.Components {
		if comp.Kind == ir.KindPostgres && comp.Postgres != nil && comp.Postgres.Schema != "" {
			if err := g.copyRequiredSourceFile(output, i.BaseDir, comp.ID, comp.Postgres.Schema, postgresSchemaPath(comp.ID)); err != nil {
				return nil, err
			}
		}
	}

	// Copy middleware config files colocated with middleware components
	for _, comp := range i.Components {
		if comp.Kind == ir.KindMiddleware && comp.Middleware != nil {
			switch comp.Middleware.Provider {
			case "better-auth":
				if comp.Middleware.Config != "" {
					if err := g.copyRequiredSourceFile(output, i.BaseDir, comp.ID, comp.Middleware.Config, middlewareConfigPath(comp.ID)); err != nil {
						return nil, err
					}
				}
			case "casbin":
				if comp.Middleware.Model != "" {
					if err := g.copyRequiredSourceFile(output, i.BaseDir, comp.ID, comp.Middleware.Model, middlewareModelPath(comp.ID)); err != nil {
						return nil, err
					}
				}
				if comp.Middleware.Policy != "" {
					if err := g.copyRequiredSourceFile(output, i.BaseDir, comp.ID, comp.Middleware.Policy, middlewarePolicyPath(comp.ID)); err != nil {
						return nil, err
					}
				}
			}
		}
	}

	// Generate .env.example
	output.AddFile(".env.example", []byte(g.generateEnvExample(i)))

	return output, nil
}

func (g *SchemaGenerator) copyRequiredSourceFile(output *codegen.Output, baseDir, componentID, sourcePath, outputPath string) error {
	content, err := g.readSourceFile(baseDir, sourcePath)
	if err != nil {
		return fmt.Errorf("component %q: failed to read source file %q: %w", componentID, sourcePath, err)
	}
	output.AddFile(outputPath, content)
	return nil
}

func (g *SchemaGenerator) readSourceFile(baseDir, relativePath string) ([]byte, error) {
	fullPath := relativePath
	if !filepath.IsAbs(relativePath) {
		fullPath = filepath.Join(baseDir, relativePath)
	}
	return os.ReadFile(fullPath)
}

func (g *SchemaGenerator) generateEnvExample(i *ir.IR) string {
	var content string
	content += "# Generated by OpenBoundary\n"
	content += "# Copy this file to .env and fill in the values\n\n"

	// Add DATABASE_URL if postgres is used
	for _, comp := range i.Components {
		if comp.Kind == ir.KindPostgres {
			content += "# Database connection string\n"
			content += "DATABASE_URL=postgres://user:password@localhost:5432/dbname\n\n"
			break
		}
	}

	return content
}
