// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	parser "github.com/stack-bound/stack-bound/internal/parser"
	mock "github.com/stretchr/testify/mock"
)

// MockNode is an autogenerated mock type for the Node type
type MockNode struct {
	mock.Mock
}

type MockNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNode) EXPECT() *MockNode_Expecter {
	return &MockNode_Expecter{mock: &_m.Mock}
}

// Pos provides a mock function with no fields
func (_m *MockNode) Pos() parser.Position {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pos")
	}

	var r0 parser.Position
	if rf, ok := ret.Get(0).(func() parser.Position); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(parser.Position)
	}

	return r0
}

// MockNode_Pos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pos'
type MockNode_Pos_Call struct {
	*mock.Call
}

// Pos is a helper method to define mock.On call
func (_e *MockNode_Expecter) Pos() *MockNode_Pos_Call {
	return &MockNode_Pos_Call{Call: _e.mock.On("Pos")}
}

func (_c *MockNode_Pos_Call) Run(run func()) *MockNode_Pos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNode_Pos_Call) Return(_a0 parser.Position) *MockNode_Pos_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNode_Pos_Call) RunAndReturn(run func() parser.Position) *MockNode_Pos_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNode creates a new instance of MockNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNode {
	mock := &MockNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
